### ISSUE TITLE
Wrong name of TAC and Outreach

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/confidentialcomputing.io#10]
https://confidentialcomputing.io/mailing-lists/ says
"Technical Advisory **Committee** (TAC)"
but in all the official docs, I believe it is always "Technical Advisory **Council** (TAC)"

**Comment by dthaler** [comment]
Also a typo on same web page: "recieve"

**Comment by dthaler** [comment]
Also I don't believe the statement "The other groups are available to member organizations, but feel free to contact us if you are interested in learning more." is correct.

The TAC list is currently open to anyone who creates a CCC account and asks to join it.

**Comment by dthaler** [comment]
Also the page says
"Marketing Committee (outreach)"
but in all the official docs, I believe it is always "Outreach Committee"

**Comment by cetola** [comment]
That page has been archived, so these issues are all gone.
