### ISSUE TITLE
Update definition of Confidential Computing

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/confidentialcomputing.io#6]
FAQ currently says: "What is confidential computing?
Confidential computing focuses on securing data in use. Current approaches in cloud computing address data at rest and in transit but encrypting data in use is considered the third and possibly most challenge step to providing a fully encrypted lifecycle for sensitive data. Confidential computing will enable encrypted data to be processed in memory without exposing it to the rest of the system. Confidential computing will reduce exposure for sensitive data and provide greater control and transparency for users."

The answer should instead say:
"Confidential Computing is the protection of data in use by performing computation in a hardware-based Trusted Execution Environment.”

**Comment by dthaler** [comment]
The text on the main web page is similarly bad (outdated):
"Confidential computing focuses on securing data in use. Current approaches to securing data often address data at rest (storage) and in transit (network) but encrypting data in use is possibly the most challenging step to providing a fully encrypted lifecycle for sensitive data. Confidential computing will enable encrypted data to be processed in memory without exposing it to the rest of the system and reduce exposure for sensitive data and provide greater control and transparency for users."

The TAC recommended, and board approved, not using "encrypted" in any way that implies constraint, so the uses of "encrypting" and "encrypted" in sentences above is considered problematic.

**Comment by cetola** [comment]
Part 1 is corrected.

Part 2: Ben and I replaced this with the updated approved positioning statement. Please review when you have a moment.
