### ISSUE TITLE
Update definition of CCC in FAQ

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/confidentialcomputing.io#7]
The FAQ currently says:
"What is the Confidential Computing Consortium?
CCC will be home to an open source community dedicated to defining and accelerating the adoption of confidential computing. It will be hosted at The Linux Foundation and embody open governance and collaboration. The effort includes commitments from Alibaba Cloud, Arm, Baidu, Google Cloud, IBM, Intel, Microsoft, Red Hat, Swisscom and Tencent."

However the wording above is all future tense, as if it hasn't formed yet.
Also the list of "commitments" should be removed since there are official members.

**Comment by dthaler** [comment]
Similarly the FAQ says:
"How will the Consortium be governed?
An open governance model consistent with open source best practices established at The Linux Foundation will be created upon formation."

Which is similarly out of date now that it's already been formed.

**Comment by cetola** [comment]
Fixed. Please review.
