### ISSUE TITLE
FAQ question is missing an answer

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/confidentialcomputing.io#9]
FAQ has "Are there other organizations addressing confidential computing? If so, why should the industry rally behind CCC?" but there is no answer text.

Either remove the question or add an answer.

**Comment by cetola** [comment]
We should define these technologies and also decide if there are organizations we want to call out as "other organizations". Clearly we want to show how we are unique as an org. Please discuss with the TAC.

This FAQ question was removed. For reference the question was:
"Are there other organizations addressing confidential computing? If so, why should the industry rally behind CCC?"

**Comment by dthaler** [comment]
Looks fine now.  In my view, the other question "How does it work with similar efforts?" overlapped with the deleted one and the answer to that one is fine.
